group: trusty_lts
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_install:
- sudo apt update -y || true
- sudo apt install -y --no-install-recommends python-pip docker-ce curl jq libxml2-utils
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
script:
- bash gradlew
- mv -f ./build/libs/*.jar /tmp/app.jar
- sudo ln -s /tmp/app.jar /etc/init.d/app
- sudo service app start
- wait_for 8080
- curl -sSXGET localhost:8080/api/v1/async -d string=test
- curl -sSXGET localhost:8080/api/v1/async-error -d string=test
- curl -sS localhost:8080/api/v1/spring/event1/test1
- curl -sS localhost:8080/api/v1/spring/event2/test2
- sudo service app stop
